### ISSUE TITLE
question GPIO26

### ISSUE THREAD

**Issue by Petervanoos** [tejasitraj/esphome-color-display#1]
In the yaml code there is also GPIO26, but in your connection diagram there is no dupont cable between the cs pin and GPIO26.
Does your display not have a cs pin? I had to make the connection to get display working.
My display has some flickering, i added the following lines tot the yaml code below 'display':

    update_interval: 10s
    auto_clear_enabled: false

There is still some flickering, but less then before.

**Comment by tejasitraj** [comment]
You're right, I don't have a CS pin on my display. Will make a note of this in my code as well as documentation. and thanks for the extra code - will try to add it in and see if it helps me. Thanks!

**Comment by tejasitraj** [comment]
Changes made.
